### PR TITLE
V8net

### PR DESCRIPTION
**Pull request by threepistons**
Addresses sudo dependency and dependency on "pi" user, to more gracefully handle multi-user environments.  See #15.

Briefly:
- Scratch GPIO now works without sudo.
- Scratch GPIO tidies up the GPIO handler on exit.
- Sample projects are with the rest of the package and are copied to the user's home folder on launch.
- A Pibrella test program is the default sample project.
- The installer doesn't need the pi user account to exist.
- The build can be done no matter where the repo is.
- I removed the desktop icons as I could not figure out how to make them for all users, they are now in the menu for all users.
- The package is installed into /opt.
- The Scratch GPIO Plus icon and launcher are no longer created as I couldn't see how they differed from the Scratch GPIO icon and launcher.

### CODE REVIEW

**Comment by cymplecy** [comment]
Note: Users should run ScratchGPIOPlus versions when working with addon boards

**Comment by cymplecy** [comment]
The basic version sets 11,12,13,15,16,18 as outputs and all other pins as inputs with pull-ups - the plus version waits to read the AddOn variable to determine which pins should be set to what default state

**Comment by cymplecy** [comment]
On pedagogical grounds  - I don't think including a full working example of a Pibrella on launch of the program is a good idea - it sort of defeats the point of learning how to do something :)

**Comment by threepistons** [comment]
> Users should run ScratchGPIOPlus versions when working with addon boards.

Ah, I didn't know about the pullups.  I didn't notice any problems with the Pibrella without them.  I can reinstate the commented-out blocks.

> On pedagogical grounds - I don't think including a full working example of a Pibrella on launch of the program is a good idea - it sort of defeats the point of learning how to do something :)

I discussed this with the class leader.  He took the view that having the Pibrella test sample launching on default was useful as it allows the supervisors to easily check the Pibrella's functioning prior to letting the students loose, and he showed me that dragging the code blocks to the left would delete them.  Perhaps this is something that I should do locally in post-install, as I can see that it would be counter-productive in other cases.

**Comment by threepistons** [comment]
The first Pibrella session this morning "all went perfectly" according to the class leader.  Thank you so much for your help.

**Comment by cymplecy** [comment]
:)

**Pull request merged**
